export type CertificateRecord = {
  id: string;
  title: string;
  issuer: string;
  issueDate: string;
  expirationDate?: string;
  category: string;
  collection?: string;
  skills: string[];
  orientation: "portrait" | "landscape" | "square";
  fileType: "image" | "pdf";
  visibility: "public" | "private" | "unlisted";
  verification: "verified" | "link" | "unavailable";
  featured: boolean;
  credentialId?: string;
  description: string;
  tone: "gold" | "charcoal" | "sage" | "blue" | "plum" | "sand";
};

export const demoCertificates: CertificateRecord[] = [
  {
    id: "google-ux",
    title: "Google UX Design Professional Certificate",
    issuer: "Google",
    issueDate: "2026-05-18",
    category: "Design",
    collection: "UX Design",
    skills: ["User research", "Figma", "Prototyping"],
    orientation: "landscape",
    fileType: "pdf",
    visibility: "public",
    verification: "verified",
    featured: true,
    credentialId: "GUX-7284-2026",
    description: "A seven-course professional certificate covering the end-to-end UX design process.",
    tone: "gold",
  },
  {
    id: "ibm-full-stack",
    title: "IBM Full Stack Software Developer",
    issuer: "IBM",
    issueDate: "2026-03-09",
    category: "Development",
    collection: "Web Development",
    skills: ["React", "Node.js", "Cloud"],
    orientation: "portrait",
    fileType: "image",
    visibility: "public",
    verification: "link",
    featured: true,
    credentialId: "IBM-FSD-4418",
    description: "Professional training across front-end, back-end, cloud-native development, and DevOps.",
    tone: "blue",
  },
  {
    id: "responsive-web",
    title: "Responsive Web Design",
    issuer: "freeCodeCamp",
    issueDate: "2025-12-14",
    category: "Development",
    collection: "Web Development",
    skills: ["HTML", "CSS", "Accessibility"],
    orientation: "landscape",
    fileType: "image",
    visibility: "public",
    verification: "verified",
    featured: false,
    description: "Applied responsive design, semantic HTML, and accessible interface patterns.",
    tone: "charcoal",
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity Fundamentals",
    issuer: "Cisco Networking Academy",
    issueDate: "2025-09-22",
    expirationDate: "2026-09-22",
    category: "Cybersecurity",
    collection: "Professional Credentials",
    skills: ["Network security", "Threat analysis"],
    orientation: "landscape",
    fileType: "pdf",
    visibility: "private",
    verification: "link",
    featured: false,
    credentialId: "CSF-2025-912",
    description: "Foundational security concepts, threat analysis, and defensive practices.",
    tone: "sage",
  },
  {
    id: "data-workshop",
    title: "Data Analytics Workshop",
    issuer: "Asia Pacific University",
    issueDate: "2025-07-06",
    expirationDate: "2026-08-30",
    category: "Data",
    collection: "Workshops",
    skills: ["SQL", "Data visualization"],
    orientation: "portrait",
    fileType: "image",
    visibility: "unlisted",
    verification: "unavailable",
    featured: false,
    description: "Hands-on workshop covering practical data preparation and analytical storytelling.",
    tone: "plum",
  },
  {
    id: "deans-award",
    title: "University Dean’s Award",
    issuer: "School of Computing",
    issueDate: "2025-04-28",
    category: "Academic",
    collection: "University",
    skills: ["Academic excellence"],
    orientation: "portrait",
    fileType: "image",
    visibility: "public",
    verification: "verified",
    featured: true,
    description: "Recognition for outstanding academic performance and contribution to the school community.",
    tone: "sand",
  },
  {
    id: "javascript",
    title: "JavaScript Algorithms and Data Structures",
    issuer: "freeCodeCamp",
    issueDate: "2025-02-10",
    category: "Development",
    collection: "Web Development",
    skills: ["JavaScript", "Algorithms"],
    orientation: "landscape",
    fileType: "pdf",
    visibility: "public",
    verification: "verified",
    featured: false,
    description: "Core JavaScript, algorithmic thinking, and practical data structures.",
    tone: "charcoal",
  },
  {
    id: "frontend-bootcamp",
    title: "Frontend Development Bootcamp",
    issuer: "Frontend Masters",
    issueDate: "2024-11-19",
    category: "Development",
    collection: "Web Development",
    skills: ["TypeScript", "React", "Testing"],
    orientation: "landscape",
    fileType: "image",
    visibility: "private",
    verification: "link",
    featured: false,
    description: "Intensive program covering modern component systems, TypeScript, and frontend testing.",
    tone: "blue",
  },
];
