"use client";

import { Award, Check } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { CertificateRecord } from "../lib/demo-certificates";

export function CertificateArtwork({
  certificate,
  compact = false,
}: {
  certificate: CertificateRecord;
  compact?: boolean;
}) {
  if (certificate.fileUrl) {
    return (
      <div
        className={`certificate-art certificate-${certificate.orientation} has-upload ${compact ? "is-compact" : ""}`}
        role="img"
        aria-label={`Preview of ${certificate.title}, issued by ${certificate.issuer}`}
      >
        {certificate.fileType === "pdf" ? (
          <PdfPagePreview
            url={certificate.fileUrl}
            label={`${certificate.title} PDF preview`}
          />
        ) : (
          // The file URL is generated by Vercel Blob and is not known at build time.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={certificate.fileUrl}
            alt={`${certificate.title}, issued by ${certificate.issuer}`}
            draggable={false}
          />
        )}
      </div>
    );
  }

  return (
    <div
      className={`certificate-art certificate-${certificate.orientation} tone-${certificate.tone} ${compact ? "is-compact" : ""}`}
      role="img"
      aria-label={`Preview of ${certificate.title}, issued by ${certificate.issuer}`}
    >
      <div className="certificate-inner">
        <Award className="certificate-crest" size={compact ? 16 : 22} strokeWidth={1.4} />
        <span className="certificate-kicker">Certificate of achievement</span>
        <strong>{certificate.title}</strong>
        <span className="certificate-line" />
        <small>{certificate.issuer}</small>
        <span className="seal"><Check size={compact ? 11 : 14} /></span>
      </div>
    </div>
  );
}

function PdfPagePreview({ url, label }: { url: string; label: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    let loadingTask: { destroy(): Promise<void> } | undefined;

    async function render() {
      try {
        const pdfjs = await import("pdfjs-dist/webpack.mjs");
        const task = pdfjs.getDocument({ url });
        loadingTask = task;
        const document = await task.promise;
        const page = await document.getPage(1);
        const natural = page.getViewport({ scale: 1 });
        const scale = Math.min(2, 1400 / natural.width);
        const viewport = page.getViewport({ scale });
        const canvas = canvasRef.current;
        if (!canvas || cancelled) return;
        canvas.width = Math.ceil(viewport.width);
        canvas.height = Math.ceil(viewport.height);
        await page.render({ canvas, viewport, background: "#ffffff" }).promise;
        await task.destroy();
        loadingTask = undefined;
      } catch {
        if (!cancelled) setFailed(true);
      }
    }

    void render();
    return () => {
      cancelled = true;
      void loadingTask?.destroy();
    };
  }, [url]);

  return failed ? (
    <span className="pdf-preview-error">PDF preview unavailable</span>
  ) : (
    <canvas ref={canvasRef} aria-label={label} />
  );
}
