import { Award, Check } from "lucide-react";
import type { CertificateRecord } from "../lib/demo-certificates";

export function CertificateArtwork({
  certificate,
  compact = false,
}: {
  certificate: CertificateRecord;
  compact?: boolean;
}) {
  if (certificate.fileUrl) {
    return (
      <div
        className={`certificate-art certificate-${certificate.orientation} has-upload ${compact ? "is-compact" : ""}`}
        role="img"
        aria-label={`Preview of ${certificate.title}, issued by ${certificate.issuer}`}
      >
        {certificate.fileType === "pdf" ? (
          <iframe
            src={`${certificate.fileUrl}#toolbar=0&navpanes=0&scrollbar=0&view=FitH`}
            title={`${certificate.title} PDF preview`}
            loading="lazy"
            tabIndex={-1}
          />
        ) : (
          // The file URL is generated by Vercel Blob and is not known at build time.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={certificate.fileUrl}
            alt={`${certificate.title}, issued by ${certificate.issuer}`}
            draggable={false}
          />
        )}
      </div>
    );
  }

  return (
    <div
      className={`certificate-art certificate-${certificate.orientation} tone-${certificate.tone} ${compact ? "is-compact" : ""}`}
      role="img"
      aria-label={`Preview of ${certificate.title}, issued by ${certificate.issuer}`}
    >
      <div className="certificate-inner">
        <Award className="certificate-crest" size={compact ? 16 : 22} strokeWidth={1.4} />
        <span className="certificate-kicker">Certificate of achievement</span>
        <strong>{certificate.title}</strong>
        <span className="certificate-line" />
        <small>{certificate.issuer}</small>
        <span className="seal"><Check size={compact ? 11 : 14} /></span>
      </div>
    </div>
  );
}
